### ISSUE TITLE
can column support title?

### ISSUE THREAD

**Issue by shaunthegeek** [tsuz/json-to-markdown-table#1]
table title is not column, such as title is "Office Address", object key is "address", code:

```
var ths = [
    'Office Address',
    'b',
    'c'
];


var object = [
    {
        address: 'efg',
        b: 'asdf,
        c: 'klm'
    },
    {
        address: 'zxcv',
        b: 'gsdf',
        c: null
    }
];
```

**Comment by tsuz** [comment]
Not supported at the moment, I can add an alias such that:

```
var ths = [
  address: {
      as: 'Office Address'
  },
  'b',
  'c'
];
```

**Comment by bala-techguy** [comment]
It will be great if you can add this feature. I was also looking for something similar to have table headers different from what is defined in json as I'm bringing the values in json format from a database.

**Comment by tsuz** [comment]
It should be solved now according to [this](https://github.com/tsuz/json-to-markdown-table/pull/2). Please let me know if this doesn't meet your needs.

**Comment by bala-techguy** [comment]
That was super fast. Thank you. I will check this out.
